"""
iam_graph/remediate.py

Phase 4 — Least-Privilege Policy Auto-Generator

Pulls the API history (CloudTrail) for a principal, diffs their granted
permissions against their actually-used permissions, and generates a
tightened least-privilege policy.
"""

from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any

# Import mock provider first to monkey-patch if MOCK_MODE is true
try:
    import common.mock_provider
except ImportError:
    pass

import boto3
from botocore.exceptions import ClientError
from dotenv import load_dotenv

load_dotenv()

logger = logging.getLogger(__name__)
logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")

REGION = os.environ.get("AWS_REGION", "us-east-1")
MOCK_MODE = os.environ.get("MOCK_MODE", "false").lower() == "true"


def generate_least_privilege_policy(
    principal_arn: str,
    dry_run: bool = True,
) -> dict[str, Any]:
    """
    Query CloudTrail for the principal's activity, compile actually used actions,
    and generate a tightened least-privilege policy.
    If dry_run is False, applies the policy to the principal.
    """
    username = principal_arn.split("/")[-1]
    principal_type = "role" if ":role/" in principal_arn else "user"

    logger.info("Generating least-privilege policy for %s %s...", principal_type, username)

    ct_client = boto3.client("cloudtrail", region_name=REGION)
    iam_client = boto3.client("iam", region_name=REGION)

    # 1. Lookup events for the principal in CloudTrail (last 90 days)
    # StartTime default is 90 days ago
    start_time = datetime.now(timezone.utc) - timedelta(days=90)
    end_time = datetime.now(timezone.utc)

    used_actions: set[str] = set()
    used_resources: set[str] = set()

    try:
        # Note: CloudTrail lookup can filter by Username attribute
        response = ct_client.lookup_events(
            LookupAttributes=[{"AttributeKey": "Username", "AttributeValue": username}],
            StartTime=start_time,
            EndTime=end_time,
            MaxResults=100
        )
        events = response.get("Events", [])
    except ClientError as e:
        logger.error("Failed to query CloudTrail for %s: %s", username, e)
        # Default to some standard safe actions in case lookup fails
        events = []

    # 2. Extract used Actions and Resources from events
    for ev in events:
        event_name = ev.get("EventName")
        
        # Read the raw Event to parse details
        ct_event_str = ev.get("CloudTrailEvent", "{}")
        try:
            ct_event = json.loads(ct_event_str)
        except json.JSONDecodeError:
            ct_event = {}

        # Resolve AWS service namespace from eventSource (e.g. s3.amazonaws.com -> s3)
        event_source = ct_event.get("eventSource", "")
        service = event_source.split(".")[0] if event_source else "s3"
        
        if event_name:
            action = f"{service}:{event_name}"
            used_actions.add(action)
            
        # Parse resources
        req_params = ct_event.get("requestParameters", {})
        if service == "s3" and "bucketName" in req_params:
            bucket = req_params["bucketName"]
            used_resources.add(f"arn:aws:s3:::{bucket}")
            used_resources.add(f"arn:aws:s3:::{bucket}/*")
        elif "resources" in ev:
            for res in ev["resources"]:
                res_name = res.get("ResourceName")
                if res_name:
                    used_resources.add(res_name)

    # Fallback to a minimal read-only list if no events were recorded
    if not used_actions:
        logger.info("No recorded CloudTrail events found. Generating a basic baseline policy.")
        used_actions = {"s3:GetObject", "s3:ListBucket"}
        used_resources = {"*"}

    # 3. Build the Policy Document
    policy_doc = {
        "Version": "2012-10-17",
        "Statement": [
            {
                "Sid": "LeastPrivilegeAutoGenerated",
                "Effect": "Allow",
                "Action": sorted(list(used_actions)),
                "Resource": sorted(list(used_resources)) if used_resources else ["*"]
            }
        ]
    }

    logger.info("Tightened policy generated: %d action(s) allowed.", len(used_actions))

    # 4. Apply policy if dry_run is False
    if not dry_run:
        policy_name = "killswitch-least-privilege"
        policy_str = json.dumps(policy_doc, indent=2)
        try:
            if principal_type == "user":
                iam_client.put_user_policy(
                    UserName=username,
                    PolicyName=policy_name,
                    PolicyDocument=policy_str
                )
            else:
                iam_client.put_role_policy(
                    RoleName=username,
                    PolicyName=policy_name,
                    PolicyDocument=policy_str
                )
            logger.warning("Applied least-privilege policy '%s' to %s %s.", policy_name, principal_type, username)
        except ClientError as e:
            logger.error("Failed to apply least-privilege policy: %s", e)

    return policy_doc


if __name__ == "__main__":
    import argparse
    parser = argparse.ArgumentParser(description="Least-Privilege Policy Generator")
    parser.add_argument("--principal", required=True, help="ARN of the principal")
    parser.add_argument("--apply", action="store_true", help="Apply policy (disables dry-run)")
    args = parser.parse_args()

    policy = generate_least_privilege_policy(args.principal, dry_run=not args.apply)
    print(json.dumps(policy, indent=2))
